version: '2'
services:
    jhipsteruaa-app:
        image: jhipsteruaa
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsteruaa-mysql:3306/jhipsteruaa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipsteruaa-mysql:
        extends:
            file: mysql.yml
            service: jhipsteruaa-mysql
